import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import { Bestseller, Bigbox, Categories, Hero, Homecompare, Marq, Videosec, Question } from '../constant';
import { Navbar } from '../components';
import Script from 'next/script';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BLABLALAPTOPS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script 
          src="https://productreviews.shopifycdn.com/assets/v4/spr-0e683603bfa450170bff33e7fbad64e7dfe9585e1caeb951bbe283e5a2306523.js"/>
        <link type="text/css" rel="stylesheet" media="screen"
          href="https://productreviews.shopifycdn.com/assets/v4/spr-07102fd76ff4bc22a3e0c32f0cca9ee51c77c34bbc4bdac79abb48f698de10dd.css"/>
          <Script  src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"/>
      </Head>
      <main className='main'>
        <Navbar home />
        <Hero />
        <Categories />
        <Marq />
        <Bigbox />
        <Bestseller />
        <Videosec />
        <Homecompare />
        <Question />
      </main>
    </>
  )
}
